# Generated by Django 2.2.7 on 2020-10-13 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvBeizeichen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='AvBeizeichen')),
            ],
            options={
                'verbose_name_plural': 'AvBeizeichen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvBildrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='AvBildrand')),
            ],
            options={
                'verbose_name_plural': 'AvBildrandgestaltung',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvBildtyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='AvBildtyp')),
            ],
            options={
                'verbose_name_plural': 'AvBildtypen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faelschung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fälschung')),
            ],
            options={
                'verbose_name_plural': 'Fälschungen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Herstellung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Herstellungsarten',
            },
        ),
        migrations.CreateModel(
            name='Herstellungsmerkmale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_nom_id', models.CharField(blank=True, max_length=250, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Herstellungsmerkmale',
            },
        ),
        migrations.CreateModel(
            name='interneAnmerkung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Anmerkung')),
            ],
        ),
        migrations.CreateModel(
            name='Metall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Metall')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Metalle',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Muenzstand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Münzstand')),
            ],
            options={
                'verbose_name_plural': 'Münzstände',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Muenztyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muenztyptitel', models.CharField(blank=True, max_length=250, null=True, verbose_name='Titel des Münztyps')),
                ('titel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titel der Münze')),
                ('dat_von', models.IntegerField(blank=True, null=True, verbose_name='Datierung von')),
                ('dat_bis', models.IntegerField(blank=True, null=True, verbose_name='Datierung bis')),
                ('dat_verb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Datierung verbale')),
                ('avleg', models.TextField(blank=True, null=True, verbose_name='Av.-Legende')),
                ('avbeschr', models.TextField(blank=True, null=True, verbose_name='Av.-Beschreibung')),
                ('rvleg', models.TextField(blank=True, null=True, verbose_name='Rv.-Legende')),
                ('rvbeschr', models.TextField(blank=True, null=True, verbose_name='Rv.-Beschreibung')),
                ('anmerkung', models.TextField(blank=True, null=True, verbose_name='Anmerkungen')),
                ('nummer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nummer')),
                ('nach', models.BooleanField(blank=True, null=True, verbose_name='Variante')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link zum Online-Typ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('Konkordanz', models.ManyToManyField(blank=True, related_name='_muenztyp_Konkordanz_+', to='slg.Muenztyp', verbose_name='Konkordanz')),
                ('Metall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Metall', verbose_name='Material')),
                ('Muenzstand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Muenzstand', verbose_name='Münzstand')),
            ],
            options={
                'verbose_name': 'Münztyp',
                'verbose_name_plural': 'Münztypen',
                'ordering': ('muenztyptitel',),
            },
        ),
        migrations.CreateModel(
            name='Mzstaette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Münzstätte')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Münzstätten',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Nominal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nominal')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Nominalien',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invnr', models.CharField(max_length=20, verbose_name='Inv.-Nr.')),
                ('fmid', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alte Filemaker-ID')),
                ('freigabe', models.BooleanField(blank=True, null=True, verbose_name='Freigabe')),
                ('titel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titel')),
                ('Typ_unsicher', models.BooleanField(blank=True, default=0, null=True, verbose_name='Typ ist unsicher')),
                ('dat_von', models.IntegerField(blank=True, null=True, verbose_name='Datierung von')),
                ('dat_bis', models.IntegerField(blank=True, null=True, verbose_name='Datierung bis')),
                ('dat_verb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Datierung verbale')),
                ('durchmesser', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Durchmesser')),
                ('gewicht', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gewicht')),
                ('stempelstellung', models.IntegerField(blank=True, choices=[(0, 'unbekannt'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, 'nicht feststellbar')], null=True, verbose_name='Stempelstellung')),
                ('avleg', models.TextField(blank=True, null=True, verbose_name='Av.-Legende')),
                ('avbeschr', models.TextField(blank=True, null=True, verbose_name='Av.-Beschreibung')),
                ('rvleg', models.TextField(blank=True, null=True, verbose_name='Rv.-Legende')),
                ('rvbeschr', models.TextField(blank=True, null=True, verbose_name='Rv.-Beschreibung')),
                ('anmerkung', models.TextField(blank=True, null=True, verbose_name='Anmerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('Herstellungsmerkmale', models.ManyToManyField(blank=True, to='slg.Herstellungsmerkmale', verbose_name='Herstellungsmerkmal')),
                ('Metall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Metall', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekte',
                'ordering': ['dat_von', 'dat_bis'],
            },
        ),
        migrations.CreateModel(
            name='Objekttyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Objekttypen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Person')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Personen',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PersonFunktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Funktion')),
            ],
            options={
                'verbose_name_plural': 'Personenrollen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Rand')),
            ],
            options={
                'verbose_name_plural': 'Randtypen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zitat', models.CharField(blank=True, max_length=200, verbose_name='Zitat')),
                ('abk', models.CharField(blank=True, max_length=30, verbose_name='Abkürzung')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Referenzen',
                'ordering': ('abk',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Region')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Regionen',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reichskreis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Reichskreise',
            },
        ),
        migrations.CreateModel(
            name='RvBeizeichen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='RvBeizeichen')),
            ],
            options={
                'verbose_name_plural': 'RvBeizeichen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RvBildrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='RvBildrand')),
            ],
            options={
                'verbose_name_plural': 'RvBildrandgestaltungen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RvBildtyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='RvBildtyp')),
            ],
            options={
                'verbose_name_plural': 'RvBildtypen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Schlagwort')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Schlagworte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sek_Merkmale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_nom_id', models.CharField(blank=True, max_length=250, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Sekundäre Merkmale',
            },
        ),
        migrations.CreateModel(
            name='Slg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sammlung')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bildurl', models.CharField(blank=True, max_length=250, null=True)),
                ('cover', models.TextField(blank=True, verbose_name='Coverbild-Url')),
            ],
            options={
                'verbose_name_plural': 'Sammlungen',
            },
        ),
        migrations.CreateModel(
            name='Variantenbeschr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name_plural': 'Varianten-Beschreibungen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Workflow')),
            ],
            options={
                'verbose_name_plural': 'Workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SlgTeil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sammlungsteil')),
                ('bildurl', models.CharField(blank=True, max_length=250, null=True)),
                ('idfk_Slg_SlgTeil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Slg', verbose_name='Sammlungsteil')),
            ],
            options={
                'verbose_name_plural': 'Sammlungsteile',
            },
        ),
        migrations.CreateModel(
            name='RvBildtyp_Schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvbildtyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.RvBildtyp')),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Schlagwort', verbose_name='Schlagwort')),
            ],
            options={
                'verbose_name_plural': 'RvBildtyp-Schlagworte',
                'unique_together': {('rvbildtyp', 'schlagwort')},
            },
        ),
        migrations.AddField(
            model_name='rvbildtyp',
            name='schlagworte',
            field=models.ManyToManyField(through='slg.RvBildtyp_Schlagwort', to='slg.Schlagwort', verbose_name='Schlagwort'),
        ),
        migrations.CreateModel(
            name='Obj_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=100, verbose_name='Nummer')),
                ('nach', models.BooleanField(verbose_name='Variante')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link zum Online-Typ')),
                ('idfk_Obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Obj')),
                ('idfk_Ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Ref', verbose_name='Zitat')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Variantenbeschr', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Referenz',
                'verbose_name_plural': 'Referenzierungen',
            },
        ),
        migrations.CreateModel(
            name='Obj_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appears_on_rev', models.BooleanField(verbose_name='am Revers')),
                ('idfk_Obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Obj')),
                ('idfk_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Person', verbose_name='Name')),
                ('idfk_PersonFunktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.PersonFunktion', verbose_name='Personenrolle')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ('idfk_PersonFunktion',),
                'unique_together': {('idfk_Obj', 'idfk_Person', 'idfk_PersonFunktion', 'appears_on_rev')},
            },
        ),
        migrations.CreateModel(
            name='Obj_interne_Anmerkung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_anmerkung', models.TextField(blank=True, null=True, verbose_name='Anmerkung (freies Textfeld)')),
                ('erledigt', models.BooleanField(blank=True, null=True, verbose_name='erledigt')),
                ('idfk_Obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Obj')),
                ('interne_Anmerkung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.interneAnmerkung', verbose_name='Anmerkung (Auswahl)')),
            ],
            options={
                'verbose_name': 'Interne Anmerkung',
                'verbose_name_plural': 'Interne Anmerkungen',
            },
        ),
        migrations.AddField(
            model_name='obj',
            name='Objekttyp',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Objekttyp', verbose_name='Objekttyp'),
        ),
        migrations.AddField(
            model_name='obj',
            name='Ppl',
            field=models.ManyToManyField(through='slg.Obj_Person', to='slg.Person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='obj',
            name='Slg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Slg', verbose_name='Sammlung'),
        ),
        migrations.AddField(
            model_name='obj',
            name='SlgTeil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.SlgTeil', verbose_name='Sammlungsteil'),
        ),
        migrations.AddField(
            model_name='obj',
            name='Typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Muenztyp', verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='obj',
            name='av_beizeichen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.AvBeizeichen', verbose_name='AvBeizeichen'),
        ),
        migrations.AddField(
            model_name='obj',
            name='av_bildrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.AvBildrand', verbose_name='AvBildrand'),
        ),
        migrations.AddField(
            model_name='obj',
            name='av_bildtyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.AvBildtyp', verbose_name='AvBildtyp'),
        ),
        migrations.AddField(
            model_name='obj',
            name='faelschung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Faelschung', verbose_name='Fälschung'),
        ),
        migrations.AddField(
            model_name='obj',
            name='idfk_Herstellung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Herstellung', verbose_name='Herstellung'),
        ),
        migrations.AddField(
            model_name='obj',
            name='idfk_Muenzstand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Muenzstand', verbose_name='Münzstand'),
        ),
        migrations.AddField(
            model_name='obj',
            name='idfk_Mzstaette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Mzstaette', verbose_name='Münzstätte'),
        ),
        migrations.AddField(
            model_name='obj',
            name='idfk_Nominal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Nominal', verbose_name='Nominal'),
        ),
        migrations.AddField(
            model_name='obj',
            name='idfk_Ref',
            field=models.ManyToManyField(through='slg.Obj_Ref', to='slg.Ref', verbose_name='Referenz'),
        ),
        migrations.AddField(
            model_name='obj',
            name='interne_anmerkungen',
            field=models.ManyToManyField(default=0, through='slg.Obj_interne_Anmerkung', to='slg.interneAnmerkung', verbose_name='interne Anmerkungen'),
        ),
        migrations.AddField(
            model_name='obj',
            name='rand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Rand', verbose_name='Rand'),
        ),
        migrations.AddField(
            model_name='obj',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='obj',
            name='rv_beizeichen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.RvBeizeichen', verbose_name='RvBeizeichen'),
        ),
        migrations.AddField(
            model_name='obj',
            name='rv_bildrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.RvBildrand', verbose_name='RvBildrand'),
        ),
        migrations.AddField(
            model_name='obj',
            name='rv_bildtyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.RvBildtyp', verbose_name='RvBildtyp'),
        ),
        migrations.AddField(
            model_name='obj',
            name='sekundaere_Merkmale',
            field=models.ManyToManyField(blank=True, to='slg.Sek_Merkmale', verbose_name='Sekundäres Merkmal'),
        ),
        migrations.AddField(
            model_name='obj',
            name='workflow',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Workflow', verbose_name='Workflow'),
        ),
        migrations.CreateModel(
            name='Mztyp_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appears_on_rev', models.BooleanField(verbose_name='am Revers')),
                ('Mztyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Muenztyp')),
                ('idfk_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Person', verbose_name='Name')),
                ('idfk_PersonFunktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.PersonFunktion', verbose_name='Personenrolle')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ('idfk_PersonFunktion',),
            },
        ),
        migrations.AddField(
            model_name='mzstaette',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='Mzstaette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Mzstaette', verbose_name='Münzstätte'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='Nominal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Nominal', verbose_name='Nominal'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='Objekttyp',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Objekttyp', verbose_name='Objekttyp'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='Ppl',
            field=models.ManyToManyField(through='slg.Mztyp_Person', to='slg.Person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='Ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Ref', verbose_name='Zitat'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='Reichskreis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Reichskreis', verbose_name='Reichskreis'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='av_beizeichen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.AvBeizeichen', verbose_name='AvBeizeichen'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='av_bildtyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.AvBildtyp', verbose_name='AvBildtyp'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='rand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Rand', verbose_name='Rand'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='rv_beizeichen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.RvBeizeichen', verbose_name='RvBeizeichen'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='rv_bildtyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.RvBildtyp', verbose_name='RvBildtyp'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Variantenbeschr', verbose_name='Variante'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='workflow',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Workflow', verbose_name='Workflow'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('erledigt', models.BooleanField(verbose_name='erledigt')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.FeedbackKategorie', verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Bemerkung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschr', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('idfk_Obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Ref')),
            ],
        ),
        migrations.CreateModel(
            name='AvBildtyp_Schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avbildtyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.AvBildtyp')),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Schlagwort', verbose_name='Schlagwort')),
            ],
            options={
                'verbose_name_plural': 'AvBildtyp-Schlagworte',
            },
        ),
        migrations.AddField(
            model_name='avbildtyp',
            name='schlagworte',
            field=models.ManyToManyField(through='slg.AvBildtyp_Schlagwort', to='slg.Schlagwort', verbose_name='Schlagwort'),
        ),
        migrations.AddIndex(
            model_name='obj',
            index=models.Index(fields=['dat_von', 'dat_bis'], name='slg_obj_dat_von_5595eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mztyp_person',
            unique_together={('Mztyp', 'idfk_Person', 'idfk_PersonFunktion', 'appears_on_rev')},
        ),
        migrations.AddIndex(
            model_name='muenztyp',
            index=models.Index(fields=['muenztyptitel'], name='slg_muenzty_muenzty_c5f6fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avbildtyp_schlagwort',
            unique_together={('avbildtyp', 'schlagwort')},
        ),
    ]
