# Generated by Django 2.2.7 on 2020-10-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='obj',
            unique_together={('invnr', 'Slg')},
        ),
    ]
