# Generated by Django 2.2.7 on 2020-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0002_auto_20201019_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muenztyp',
            name='muenztyptitel',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Titel des Münztyps'),
        ),
    ]
