# Generated by Django 2.2.7 on 2020-11-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0003_auto_20201019_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=100, verbose_name='Seiten von-bis')),
                ('Ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Ref', verbose_name='Zitat')),
                ('Typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Muenztyp')),
            ],
            options={
                'verbose_name': 'Literatur',
                'verbose_name_plural': 'Literatur',
            },
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='Literatur',
            field=models.ManyToManyField(related_name='Erweiterte_Literatur', through='slg.Typ_Ref', to='slg.Ref', verbose_name='Weitere Literatur'),
        ),
    ]
