# Generated by Django 2.2.7 on 2020-11-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0004_auto_20201101_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name',), 'verbose_name_plural': 'Personen/Organisationen'},
        ),
        migrations.AlterModelOptions(
            name='typ_ref',
            options={'verbose_name': 'Ergänzende Literatur', 'verbose_name_plural': 'Ergänzende Literatur'},
        ),
        migrations.AddField(
            model_name='nominal',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Metall', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='person',
            name='beschreibung',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AddField(
            model_name='person',
            name='dat_geboren',
            field=models.IntegerField(blank=True, null=True, verbose_name='Geboren im Jahr'),
        ),
        migrations.AddField(
            model_name='person',
            name='dat_gestorben',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gestorben im Jahr'),
        ),
        migrations.AddField(
            model_name='person',
            name='dat_verb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Datierung verbale'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Person/Organisation'),
        ),
        migrations.AlterField(
            model_name='typ_ref',
            name='Ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Ref', verbose_name='Literatur'),
        ),
    ]
