# Generated by Django 2.2.7 on 2020-12-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0005_auto_20201108_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='muenztyp',
            name='Herstellung',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Herstellung', verbose_name='Herstellung'),
        ),
    ]
