# Generated by Django 2.2.7 on 2021-01-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0006_muenztyp_herstellung'),
    ]

    operations = [
        migrations.AddField(
            model_name='avbildtyp',
            name='abk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Abkürzung'),
        ),
    ]
