# Generated by Django 2.2.7 on 2021-01-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0007_avbildtyp_abk'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvbildtyp',
            name='abk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Abkürzung'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='Metall',
            field=models.ForeignKey(blank=True, help_text='optionales Autofill basierend auf der Angabe beim Nominal', null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Metall', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='av_bildtyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avmztypen', to='slg.AvBildtyp', verbose_name='AvBildtyp'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='dat_verb',
            field=models.CharField(blank=True, help_text='optionales Autofill basierend auf den Datierungsfeldern', max_length=100, null=True, verbose_name='Datierung verbale'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='muenztyptitel',
            field=models.CharField(blank=True, help_text='optionales Autofill basierend auf: Zitat + Zitatnr. + Variante', max_length=250, null=True, unique=True, verbose_name='Titel des Münztyps'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='region',
            field=models.ForeignKey(blank=True, help_text='optionales Autofill basierend auf der Angabe bei der Münzstätte', null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='rv_bildtyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rvmztypen', to='slg.RvBildtyp', verbose_name='RvBildtyp'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='titel',
            field=models.CharField(blank=True, help_text='optionales Autofill basierend auf: Münzstand + Münzstätte + Münzherr/-en', max_length=200, null=True, verbose_name='Titel der Münze'),
        ),
        migrations.AlterField(
            model_name='obj',
            name='Typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objekte', to='slg.Muenztyp', verbose_name='Typ'),
        ),
    ]
