# Generated by Django 2.2.7 on 2021-01-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0008_auto_20210111_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mztyp_Schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mztyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Muenztyp')),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Schlagwort', verbose_name='Schlagwort')),
            ],
            options={
                'verbose_name': 'Schlagwort',
                'verbose_name_plural': 'Verschlagwortung',
                'unique_together': {('mztyp', 'schlagwort')},
            },
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='schlagworte',
            field=models.ManyToManyField(through='slg.Mztyp_Schlagwort', to='slg.Schlagwort', verbose_name='Schlagwort'),
        ),
    ]
