# Generated by Django 2.2.7 on 2021-01-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0009_auto_20210112_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dat_verb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lebensdaten verbale'),
        ),
        migrations.CreateModel(
            name='Person_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=100, verbose_name='Nummer')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Webseite')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Person')),
                ('Ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Ref', verbose_name='Seitenzahl')),
            ],
            options={
                'verbose_name': 'Literatur',
                'verbose_name_plural': 'Literatur',
            },
        ),
    ]
