# Generated by Django 2.2.7 on 2021-01-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0010_auto_20210112_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='zeichen',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zeichen'),
        ),
        migrations.AlterField(
            model_name='person_ref',
            name='Ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Ref', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person_ref',
            name='nummer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seitenzahl'),
        ),
    ]
