# Generated by Django 2.2.7 on 2021-01-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0011_auto_20210112_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muenztyp',
            name='Metall',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Metall', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='dat_verb',
            field=models.CharField(blank=True, help_text='optional', max_length=100, null=True, verbose_name='Datierung verbale'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='muenztyptitel',
            field=models.CharField(blank=True, help_text='optional (Zitat + Zitatnr. + Variante)', max_length=250, null=True, unique=True, verbose_name='Titel des Münztyps'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='region',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='titel',
            field=models.CharField(blank=True, help_text='optional (Münzstand + Münzstätte + Münzherr/-en)', max_length=200, null=True, verbose_name='Titel der Münze'),
        ),
        migrations.CreateModel(
            name='Mztyp_interne_Anmerkung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_anmerkung', models.TextField(blank=True, null=True, verbose_name='Anmerkung (freies Textfeld)')),
                ('erledigt', models.BooleanField(blank=True, null=True, verbose_name='erledigt')),
                ('Mztyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Muenztyp')),
                ('interne_Anmerkung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.interneAnmerkung', verbose_name='Anmerkung (Auswahl)')),
            ],
            options={
                'verbose_name': 'Interne Anmerkung',
                'verbose_name_plural': 'Interne Anmerkungen',
            },
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='interne_anmerkungen',
            field=models.ManyToManyField(default=0, through='slg.Mztyp_interne_Anmerkung', to='slg.interneAnmerkung', verbose_name='interne Anmerkungen'),
        ),
    ]
