# Generated by Django 2.2.7 on 2021-01-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0012_auto_20210112_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlgInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_von', models.IntegerField(blank=True, null=True, verbose_name='Datierung von')),
                ('dat_bis', models.IntegerField(blank=True, null=True, verbose_name='Datierung bis')),
                ('dat_verb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Datierung verbale')),
                ('information', models.TextField(blank=True, max_length=250, verbose_name='Information')),
            ],
            options={
                'verbose_name': 'Ereignis',
                'verbose_name_plural': 'Ereignisse',
                'ordering': ('-dat_von', 'dat_bis'),
            },
        ),
        migrations.AlterModelOptions(
            name='interneanmerkung',
            options={'ordering': ('name',), 'verbose_name': 'Interne Anmerkung', 'verbose_name_plural': 'Interne Anmerkungen'},
        ),
        migrations.AlterModelOptions(
            name='mztyp_interne_anmerkung',
            options={'ordering': ('interne_Anmerkung',), 'verbose_name': 'Interne Anmerkung', 'verbose_name_plural': 'Interne Anmerkungen'},
        ),
        migrations.AlterModelOptions(
            name='obj_interne_anmerkung',
            options={'ordering': ('interne_Anmerkung',), 'verbose_name': 'Interne Anmerkung', 'verbose_name_plural': 'Interne Anmerkungen'},
        ),
        migrations.AlterModelOptions(
            name='obj_ref',
            options={'verbose_name': 'Literatur', 'verbose_name_plural': 'Literatur, in der das Objekt erwähnt wird'},
        ),
        migrations.AlterField(
            model_name='mztyp_interne_anmerkung',
            name='Mztyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intanmerkungen', to='slg.Muenztyp'),
        ),
        migrations.AlterField(
            model_name='obj_interne_anmerkung',
            name='idfk_Obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intanmerkungen', to='slg.Obj'),
        ),
        migrations.AlterField(
            model_name='slg',
            name='bildurl',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Url zum Bilderverzeichnis'),
        ),
        migrations.AlterField(
            model_name='slg',
            name='cover',
            field=models.CharField(blank=True, max_length=250, verbose_name='Coverbild-Url'),
        ),
        migrations.CreateModel(
            name='SlgInformation_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seitenzahl')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Webseite')),
                ('Ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zitate', to='slg.Ref', verbose_name='Name')),
                ('Slginfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.SlgInformation')),
            ],
            options={
                'verbose_name': 'Zitat',
                'verbose_name_plural': 'Zitate zum Ereignis',
            },
        ),
        migrations.AddField(
            model_name='slginformation',
            name='Slg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Slg'),
        ),
        migrations.AddField(
            model_name='slginformation',
            name='objekte',
            field=models.ManyToManyField(blank=True, to='slg.Obj', verbose_name='Objekte'),
        ),
        migrations.AddField(
            model_name='slginformation',
            name='person',
            field=models.ManyToManyField(blank=True, to='slg.Person', verbose_name='Person/Organisation'),
        ),
    ]
