# Generated by Django 2.2.7 on 2021-01-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0013_auto_20210116_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slginformation',
            name='information',
            field=models.TextField(blank=True, verbose_name='Information'),
        ),
    ]
