# Generated by Django 2.2.7 on 2021-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0014_auto_20210116_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Benediktinerlexikon',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (Benediktinerlexikon)'),
        ),
        migrations.AddField(
            model_name='person',
            name='BiographiePortal',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (Biographie-Portal)'),
        ),
        migrations.AddField(
            model_name='person',
            name='DNB',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (Deutsche National Bibliothek)'),
        ),
        migrations.AddField(
            model_name='person',
            name='DeutscheDigitaleBib',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (Deutsche Digitale Bibliothek)'),
        ),
        migrations.AddField(
            model_name='person',
            name='GeschichteWikiWien',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (WienGeschichteWiki)'),
        ),
        migrations.AddField(
            model_name='person',
            name='VIAF',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (VIAF)'),
        ),
        migrations.AddField(
            model_name='person',
            name='WikiDe',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (dt. Wiki)'),
        ),
        migrations.AddField(
            model_name='person',
            name='WikiEn',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (eng. Wiki)'),
        ),
        migrations.AddField(
            model_name='person',
            name='Zisterzienserlexikon',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (Zisterzienserlexikon)'),
        ),
    ]
