# Generated by Django 2.2.7 on 2021-01-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0015_auto_20210116_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slginformation_ref',
            options={'verbose_name': 'Quelle', 'verbose_name_plural': 'Quelle/n zum Ereignis'},
        ),
        migrations.AddField(
            model_name='person',
            name='DB',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (Deutsche Biographie)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='DNB',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (DNB Deutsche National Bibliothek)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='DeutscheDigitaleBib',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (DDB Deutsche Digitale Bibliothek)'),
        ),
    ]
