# Generated by Django 2.2.7 on 2021-01-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0016_auto_20210117_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['reihenfolge'], 'verbose_name_plural': 'Workflows'},
        ),
        migrations.AddField(
            model_name='workflow',
            name='reihenfolge',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zeichen',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zeichen/Signatur'),
        ),
    ]
