# Generated by Django 2.2.7 on 2021-01-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0017_auto_20210121_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muenztyp',
            options={'ordering': ('dat_von',), 'verbose_name': 'Münztyp', 'verbose_name_plural': 'Münztypen'},
        ),
        migrations.RemoveIndex(
            model_name='muenztyp',
            name='slg_muenzty_muenzty_c5f6fd_idx',
        ),
        migrations.AddIndex(
            model_name='muenztyp',
            index=models.Index(fields=['dat_von'], name='slg_muenzty_dat_von_b968b4_idx'),
        ),
    ]
