# Generated by Django 2.2.7 on 2021-01-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0018_auto_20210121_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='OeBL',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (Österreich. Biographisches Lexikon)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='DNB',
            field=models.URLField(blank=True, help_text='Format: http://d-nb.info/gnd/133079139', max_length=255, null=True, verbose_name='URL (GND/DNB Deutsche National Bibliothek)'),
        ),
    ]
