# Generated by Django 2.2.7 on 2021-07-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0019_auto_20210122_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='muenztyp',
            name='av_bildrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.AvBildrand', verbose_name='AvBildrand'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='rv_bildrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.RvBildrand', verbose_name='RvBildrand'),
        ),
        migrations.AddField(
            model_name='obj',
            name='Untertyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OUntertyp', to='slg.Muenztyp', verbose_name='Untertyp'),
        ),
        migrations.AddField(
            model_name='obj',
            name='Untertyp_unsicher',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Typ ist unsicher'),
        ),
        migrations.AlterField(
            model_name='person',
            name='DNB',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (GND/DNB Deutsche National Bibliothek)'),
        ),
    ]
