# Generated by Django 2.2.7 on 2021-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0020_auto_20210715_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj',
            name='TempTyp',
            field=models.TextField(blank=True, null=True, verbose_name='TempTyp'),
        ),
    ]
