# Generated by Django 2.2.7 on 2021-10-20 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0021_obj_temptyp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titel')),
                ('nummer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nummer')),
                ('katalogteil', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teil')),
                ('anzahl', models.PositiveIntegerField(blank=True, null=True, verbose_name='Anzahl der Objekte')),
                ('tag_von', models.IntegerField(blank=True, null=True, verbose_name='Tag von')),
                ('tag_bis', models.IntegerField(blank=True, null=True, verbose_name='Tag bis')),
                ('jahr', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jahr')),
                ('tafelteil', models.BooleanField(verbose_name='Tafeln')),
                ('anmerkung', models.TextField(blank=True, verbose_name='Anmerkung')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Katalog',
                'verbose_name_plural': 'Kataloge',
                'ordering': ['katalogart', 'jahr', 'monat', 'tag_von'],
            },
        ),
        migrations.CreateModel(
            name='Katalogart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Katalogart',
                'verbose_name_plural': 'Katalogarten',
            },
        ),
        migrations.CreateModel(
            name='Monat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sortierung', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Monat',
                'verbose_name_plural': 'Monate',
            },
        ),
        migrations.CreateModel(
            name='Staat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MyObjects',
            fields=[
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Liste: Objekte',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('slg.obj',),
        ),
        migrations.CreateModel(
            name='Onlineressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Link')),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Firma', verbose_name='Firma')),
                ('katalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Katalog', verbose_name='Katalog')),
            ],
        ),
        migrations.CreateModel(
            name='KatalogFirmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Firma')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Katalog')),
            ],
            options={
                'verbose_name': 'KatalogFirmen',
                'verbose_name_plural': 'KatalogFirmen',
                'unique_together': {('katalog', 'firma')},
            },
        ),
        migrations.AddField(
            model_name='katalog',
            name='firmen',
            field=models.ManyToManyField(through='slg.KatalogFirmen', to='slg.Firma', verbose_name='Firmen'),
        ),
        migrations.AddField(
            model_name='katalog',
            name='katalogart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Katalogart', verbose_name='Katalogart'),
        ),
        migrations.AddField(
            model_name='katalog',
            name='monat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Monat', verbose_name='Monat/Jahreszeit'),
        ),
        migrations.AddField(
            model_name='katalog',
            name='staat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Staat', verbose_name='Staat'),
        ),
        migrations.AddField(
            model_name='katalog',
            name='workflow',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Workflow', verbose_name='Workflow'),
        ),
    ]
