# Generated by Django 2.2.7 on 2021-10-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0022_auto_20211020_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineressource',
            name='name',
            field=models.CharField(max_length=350, verbose_name='Link'),
        ),
    ]
