# Generated by Django 2.2.7 on 2021-10-20 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0023_auto_20211020_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
