# Generated by Django 2.2.7 on 2021-10-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0024_auto_20211020_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='created_at',
        ),
    ]
