# Generated by Django 2.2.7 on 2021-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0025_remove_katalog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineressource',
            name='name',
            field=models.URLField(blank=True, null=True, verbose_name='Link zum Online-Typ'),
        ),
    ]
