# Generated by Django 2.2.7 on 2021-10-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0026_auto_20211020_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineressource',
            name='name',
        ),
    ]
