# Generated by Django 2.2.7 on 2021-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0027_remove_onlineressource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineressource',
            name='name',
            field=models.URLField(blank=True, null=True, verbose_name='Link zum Online-Typ'),
        ),
    ]
