# Generated by Django 2.2.7 on 2021-10-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0028_onlineressource_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KatSchlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Schlagwort')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
            ],
            options={
                'verbose_name_plural': 'Schlagworte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KatalogSchlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Katalog')),
                ('katschlagwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.KatSchlagwort', verbose_name='Schlagwort')),
            ],
            options={
                'verbose_name_plural': 'Verschlagwortung',
                'unique_together': {('katalog', 'katschlagwort')},
            },
        ),
    ]
