# Generated by Django 2.2.7 on 2021-10-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0029_katalogschlagwort_katschlagwort'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='schlagworte',
            field=models.ManyToManyField(through='slg.KatalogSchlagwort', to='slg.KatSchlagwort', verbose_name='Schlagwort'),
        ),
    ]
