# Generated by Django 2.2.7 on 2021-10-27 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0030_katalog_schlagworte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
