# Generated by Django 2.2.7 on 2021-10-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0031_auto_20211027_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katalogschlagwort',
            options={'ordering': ['katschlagwort'], 'verbose_name_plural': 'Verschlagwortung'},
        ),
        migrations.AddField(
            model_name='onlineressource',
            name='temp',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Temp'),
        ),
        migrations.AlterField(
            model_name='onlineressource',
            name='katalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hlinks', to='slg.Katalog', verbose_name='Katalog'),
        ),
    ]
