# Generated by Django 2.2.7 on 2021-11-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0032_auto_20211029_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='tafelanzahl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anzahl der Tafeln'),
        ),
    ]
