# Generated by Django 2.2.7 on 2021-11-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0033_katalog_tafelanzahl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='tafelanzahl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='T.-Anzahl'),
        ),
    ]
