# Generated by Django 2.2.7 on 2021-11-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0034_auto_20211106_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='KatalogPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idfk_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Person', verbose_name='Name')),
                ('idfk_PersonFunktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.PersonFunktion', verbose_name='Personenrolle')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Katalog')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ('idfk_PersonFunktion',),
                'unique_together': {('katalog', 'idfk_Person', 'idfk_PersonFunktion')},
            },
        ),
        migrations.AddField(
            model_name='katalog',
            name='Ppl',
            field=models.ManyToManyField(through='slg.KatalogPerson', to='slg.Person', verbose_name='Person'),
        ),
    ]
