# Generated by Django 2.2.7 on 2021-11-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0035_auto_20211109_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalogperson',
            name='katalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sammler', to='slg.Katalog'),
        ),
    ]
