# Generated by Django 2.2.7 on 2021-11-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0036_auto_20211109_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katalogperson',
            options={'ordering': ('personfunktion',), 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.RenameField(
            model_name='katalogperson',
            old_name='idfk_Person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='katalogperson',
            old_name='idfk_PersonFunktion',
            new_name='personfunktion',
        ),
        migrations.AddField(
            model_name='katschlagwort',
            name='synonyme',
            field=models.TextField(blank=True, null=True, verbose_name='Synonyme'),
        ),
        migrations.AlterUniqueTogether(
            name='katalogperson',
            unique_together={('katalog', 'person', 'personfunktion')},
        ),
    ]
