# Generated by Django 2.2.7 on 2021-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0038_auto_20211127_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mmlo',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL (Biographisches Lexikon der Münzmeister und Wardeine, Stempelschneider und Medailleure)'),
        ),
    ]
