# Generated by Django 2.2.7 on 2022-03-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0039_person_mmlo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slgsart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sammlung')),
            ],
            options={
                'verbose_name_plural': 'Sammlungsarten',
            },
        ),
        migrations.AlterField(
            model_name='avbildtyp',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='AvBildtyp'),
        ),
        migrations.AlterField(
            model_name='mzstaette',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Münzstätte'),
        ),
        migrations.AlterField(
            model_name='rvbildtyp',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='RvBildtyp'),
        ),
        migrations.AddField(
            model_name='slg',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Slgsart', verbose_name='Sammlungsart'),
        ),
    ]
