# Generated by Django 2.2.7 on 2022-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0040_auto_20220327_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slgsart',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Sammlungsart'),
        ),
    ]
