# Generated by Django 2.2.7 on 2022-03-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0041_auto_20220327_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slg',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Slgsart', verbose_name='Sammlungsart'),
        ),
    ]
