# Generated by Django 2.2.7 on 2022-03-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0042_auto_20220327_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slg',
            name='kategorie',
        ),
    ]
