# Generated by Django 2.2.7 on 2022-04-02 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0043_remove_slg_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slg',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
