# Generated by Django 2.2.7 on 2022-04-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0044_auto_20220402_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wappen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Wappen')),
                ('beschreibung', models.CharField(blank=True, max_length=250, verbose_name='Kurzbeschreibung')),
            ],
            options={
                'verbose_name_plural': 'Wappen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mztyp_Wappen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appears_on_rev', models.BooleanField(verbose_name='am Revers')),
                ('mztyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Muenztyp')),
                ('wappen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Wappen', verbose_name='Wappen')),
            ],
            options={
                'verbose_name': 'Wappen',
                'verbose_name_plural': 'Wappen',
                'unique_together': {('mztyp', 'wappen', 'appears_on_rev')},
            },
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='wappen',
            field=models.ManyToManyField(through='slg.Mztyp_Wappen', to='slg.Wappen', verbose_name='Wappen'),
        ),
    ]
