# Generated by Django 2.2.7 on 2022-07-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0045_auto_20220410_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvOffizin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='AvOffizin')),
            ],
            options={
                'verbose_name_plural': 'AvOffizin',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RvOffizin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='RvOffizin')),
            ],
            options={
                'verbose_name_plural': 'RvOffizin',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='mztyp_wappen',
            name='appears_on_rev',
            field=models.BooleanField(default=1, verbose_name='am Revers'),
        ),
        migrations.AddField(
            model_name='obj',
            name='av_offizin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.AvOffizin', verbose_name='AvOffizin'),
        ),
        migrations.AddField(
            model_name='obj',
            name='rv_offizin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.RvOffizin', verbose_name='RvOffizin'),
        ),
    ]
