# Generated by Django 2.2.7 on 2022-07-30 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0046_auto_20220726_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muenztyp',
            name='rv_beizeichen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rvbeizeichen', to='slg.RvBeizeichen', verbose_name='RvBeizeichen'),
        ),
    ]
