# Generated by Django 2.2.7 on 2023-06-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0047_auto_20220730_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maßnahmennr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Maßnahmen-Nr.')),
                ('fundnummer', models.IntegerField(blank=True, null=True, verbose_name='Fundnummer')),
                ('fundnummerzusatz', models.CharField(blank=True, max_length=2, null=True, verbose_name='Fundnummerzusatz')),
                ('kistennr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kisten-Nr.')),
                ('parzelle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Parzelle')),
                ('fundstelle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fundstelle')),
                ('lm_von', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Laufmeter von')),
                ('lm_bis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Laufmeter bis')),
                ('niveautiefe_in_m_von', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Niveautiefe in m von')),
                ('niveautiefe_in_m_bis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Niveautiefe in m bis')),
                ('niveau', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Niveau')),
                ('vn', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='von Norden')),
                ('vno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='von Nordosten')),
                ('vo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='von Osten')),
                ('vso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='von Südosten')),
                ('vs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='von Süden')),
                ('vsw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='von Südwesten')),
                ('vw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='von Westen')),
                ('vnw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='von Nordwesten')),
                ('schnitt', models.CharField(blank=True, max_length=5, null=True, verbose_name='Schnitt')),
                ('bereichsbezeichnung', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bereichsbezeichnung')),
                ('sondage', models.IntegerField(blank=True, null=True, verbose_name='Sondage')),
                ('quadrant', models.IntegerField(blank=True, null=True, verbose_name='Quadrant')),
                ('flaeche', models.CharField(blank=True, max_length=25, null=True, verbose_name='Fläche')),
                ('se', models.IntegerField(blank=True, null=True, verbose_name='Stratigraphische Einheit')),
                ('stratum', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stratum')),
                ('funddatum', models.DateTimeField(blank=True, null=True, verbose_name='Funddatum')),
                ('andere_materialien', models.CharField(blank=True, max_length=225, null=True, verbose_name='Fundmaterial')),
                ('fundposition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fundposition')),
                ('anmerkung', models.CharField(blank=True, max_length=225, null=True, verbose_name='Anmerkung')),
                ('bearbeiter', models.CharField(blank=True, max_length=225, null=True, verbose_name='Fundzettel erfasst von')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Obj', verbose_name='Objekt')),
                ('zusammen_gefundene_muenzen', models.ManyToManyField(blank=True, null=True, related_name='_fund_zusammen_gefundene_muenzen_+', to='slg.Fund', verbose_name='Zusammen gefundene Münzen')),
            ],
            options={
                'verbose_name': 'Fundinformation',
                'verbose_name_plural': 'Fundinformationen',
                'ordering': ('maßnahmennr', 'fundnummer'),
            },
        ),
    ]
