# Generated by Django 2.2.7 on 2023-06-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0048_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='objekt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slg.Obj', verbose_name='Objekt'),
        ),
    ]
