# Generated by Django 2.2.7 on 2023-06-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0049_auto_20230607_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fundjahr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fundjahr'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='funddatum',
            field=models.DateField(blank=True, null=True, verbose_name='Funddatum'),
        ),
    ]
