# Generated by Django 2.2.7 on 2023-06-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0050_auto_20230607_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='andere_materialien',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Sonstiges Fundmaterial'),
        ),
    ]
