# Generated by Django 2.2.7 on 2023-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0051_auto_20230607_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fundkontext',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='fundkontext'),
        ),
    ]
