# Generated by Django 2.2.7 on 2023-06-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0052_fund_fundkontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='quadrantzusatz',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Quadrant-Zusatz'),
        ),
    ]
