# Generated by Django 2.2.7 on 2023-09-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0054_auto_20230825_0904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='obj',
            unique_together={('invnr', 'Slg', 'SlgTeil')},
        ),
    ]
