# Generated by Django 2.2.7 on 2023-10-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0055_auto_20230907_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='vn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='von Norden (mm)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='vno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='von Nordosten (mm)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='vnw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='von Nordwesten (mm)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='vo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='von Osten (mm)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='vs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='von Süden (mm)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='vso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='von Südosten (mm)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='vsw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='von Südwesten (mm)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='vw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='von Westen (mm)'),
        ),
    ]
