# Generated by Django 2.2.7 on 2023-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0056_auto_20231019_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj',
            name='abnutzung',
            field=models.IntegerField(blank=True, choices=[(1, '1 - nicht bis kaum abgenutzt'), (2, '2 - leicht abgenutzt'), (3, '3 - abgenutzt'), (4, '4 - stark abgenutzt'), (5, '5 - sehr stark bis ganz abgenutzt')], null=True, verbose_name='Abnutzung'),
        ),
    ]
