# Generated by Django 2.2.7 on 2023-11-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0057_obj_abnutzung'),
    ]

    operations = [
        migrations.AddField(
            model_name='slginformation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AddField(
            model_name='slginformation',
            name='quellen',
            field=models.ManyToManyField(blank=True, related_name='ereignisse', to='slg.Ref'),
        ),
        migrations.CreateModel(
            name='Datierung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumstyp', models.CharField(choices=[('Exaktes Datum', 'Exaktes Datum'), ('Zeitraum', 'Zeitraum'), ('Jahr', 'Jahr'), ('Monat', 'Monat'), ('Jahreszeit', 'Jahreszeit')], max_length=50)),
                ('datum_genau', models.DateField(blank=True, null=True)),
                ('jahr_start', models.IntegerField(blank=True, null=True)),
                ('jahr_ende', models.IntegerField(blank=True, null=True)),
                ('monat_von', models.IntegerField(blank=True, null=True)),
                ('monat_bis', models.IntegerField(blank=True, null=True)),
                ('zusaetzliche_beschreibung', models.CharField(blank=True, max_length=200, null=True)),
                ('unsicher', models.BooleanField(default=False)),
                ('gesamterzeitraum', models.BooleanField(default=False)),
                ('ereignis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.SlgInformation')),
                ('quellen', models.ManyToManyField(blank=True, to='slg.Ref')),
            ],
        ),
    ]
