# Generated by Django 2.2.7 on 2023-11-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0058_auto_20231118_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slginformation',
            name='quellen',
        ),
    ]
