# Generated by Django 2.2.7 on 2023-11-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0059_remove_slginformation_quellen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datierung',
            old_name='datum_genau',
            new_name='datum_genau_bis',
        ),
        migrations.AddField(
            model_name='datierung',
            name='datum_genau_von',
            field=models.DateField(blank=True, null=True),
        ),
    ]
