# Generated by Django 2.2.7 on 2023-11-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0060_auto_20231118_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datierung',
            name='quellen',
        ),
        migrations.AddField(
            model_name='datierung',
            name='verweis',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='datierung',
            name='zitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Ref'),
        ),
    ]
