# Generated by Django 2.2.7 on 2023-11-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0061_auto_20231118_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datierung',
            name='datum_genau_bis',
        ),
        migrations.RemoveField(
            model_name='datierung',
            name='datum_genau_von',
        ),
        migrations.AddField(
            model_name='datierung',
            name='tag_bis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datierung',
            name='tag_von',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
