# Generated by Django 2.2.7 on 2023-11-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0062_auto_20231118_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datierung',
            name='datumstyp',
        ),
    ]
