# Generated by Django 2.2.7 on 2023-12-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0063_remove_datierung_datumstyp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuenztypObjektAnzeige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invnr', models.CharField(max_length=20, verbose_name='Inventarnummer')),
                ('objekttitel', models.CharField(max_length=200, verbose_name='Titel des Objekts')),
                ('objekttyp', models.CharField(max_length=100, verbose_name='Objekttyp')),
                ('herstellung', models.CharField(max_length=100, verbose_name='Herstellung')),
                ('reichskreis', models.CharField(max_length=100, verbose_name='Reichskreis')),
                ('muenzstand', models.CharField(max_length=100, verbose_name='Münzstand')),
                ('nominal', models.CharField(max_length=100, verbose_name='Nominal')),
                ('metall', models.CharField(max_length=100, verbose_name='Material')),
                ('mzstaette', models.CharField(max_length=100, verbose_name='Münzstätte')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('datierung_von', models.IntegerField(blank=True, null=True, verbose_name='Datierung von')),
                ('datierung_bis', models.IntegerField(blank=True, null=True, verbose_name='Datierung bis')),
                ('datierung_verbale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Datierung verbale')),
                ('durchmesser', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Durchmesser')),
                ('gewicht', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gewicht')),
                ('stempelstellung', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stempelstellung')),
                ('abnutzung', models.CharField(blank=True, max_length=100, null=True, verbose_name='Abnutzung')),
                ('av_legende', models.TextField(blank=True, null=True, verbose_name='Av.-Legende')),
                ('av_bildtyp', models.CharField(blank=True, max_length=100, null=True, verbose_name='AvBildtyp')),
                ('av_beizeichen', models.CharField(blank=True, max_length=100, null=True, verbose_name='AvBeizeichen')),
                ('av_bildrand', models.CharField(blank=True, max_length=100, null=True, verbose_name='AvBildrand')),
                ('rv_legende', models.TextField(blank=True, null=True, verbose_name='Rv.-Legende')),
                ('rv_bildtyp', models.CharField(blank=True, max_length=100, null=True, verbose_name='RvBildtyp')),
                ('rv_beizeichen', models.CharField(blank=True, max_length=100, null=True, verbose_name='RvBeizeichen')),
                ('rv_bildrand', models.CharField(blank=True, max_length=100, null=True, verbose_name='RvBildrand')),
                ('rand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rand')),
                ('anmerkungen', models.TextField(blank=True, null=True, verbose_name='Anmerkungen')),
                ('typ', models.CharField(blank=True, max_length=100, null=True, verbose_name='Typ')),
                ('typlink', models.URLField(blank=True, null=True, verbose_name='Link zum Online-Typ')),
                ('konkordanz', models.TextField(blank=True, null=True, verbose_name='Konkordanz')),
                ('personen_av', models.TextField(blank=True, null=True, verbose_name='Personen Av')),
                ('personen_rv', models.TextField(blank=True, null=True, verbose_name='Personen Rv')),
                ('personen_sonstige', models.TextField(blank=True, null=True, verbose_name='Sonstige Personen')),
            ],
        ),
        migrations.AddField(
            model_name='slg',
            name='bild_endung_av',
            field=models.CharField(default='a00', max_length=10, verbose_name='Endung Vorderseite'),
        ),
        migrations.AddField(
            model_name='slg',
            name='bild_endung_rv',
            field=models.CharField(default='r00', max_length=10, verbose_name='Endung Rückseite'),
        ),
        migrations.AddField(
            model_name='slgteil',
            name='bild_endung_av',
            field=models.CharField(default='Av', max_length=10, verbose_name='Endung Vorderseite'),
        ),
        migrations.AddField(
            model_name='slgteil',
            name='bild_endung_rv',
            field=models.CharField(default='Rv', max_length=10, verbose_name='Endung Rückseite'),
        ),
    ]
