# Generated by Django 2.2.7 on 2023-12-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0064_auto_20231206_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slgteil',
            name='bild_endung_av',
            field=models.CharField(blank=True, default='a00', max_length=10, null=True, verbose_name='Endung Vorderseite'),
        ),
        migrations.AlterField(
            model_name='slgteil',
            name='bild_endung_rv',
            field=models.CharField(blank=True, default='r00', max_length=10, null=True, verbose_name='Endung Rückseite'),
        ),
    ]
