# Generated by Django 2.2.7 on 2023-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0065_auto_20231206_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='slg',
            name='entferne_zeichen',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zu entfernende Zeichen hinsichtlich der Abb.'),
        ),
        migrations.AddField(
            model_name='slgteil',
            name='entferne_zeichen',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zu entfernende Zeichen hinsichtlich der Abb.'),
        ),
    ]
