# Generated by Django 2.2.7 on 2023-12-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0066_auto_20231206_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='herstellung',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Herstellung'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='metall',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='muenzstand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Münzstand'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='mzstaette',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Münzstätte'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='nominal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nominal'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='objekttitel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titel des Objekts'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='objekttyp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Objekttyp'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='reichskreis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reichskreis'),
        ),
    ]
