# Generated by Django 2.2.7 on 2023-12-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0067_auto_20231209_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='av_bildtyp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AvBildtyp'),
        ),
        migrations.AlterField(
            model_name='muenztypobjektanzeige',
            name='rv_bildtyp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RvBildtyp'),
        ),
    ]
