# Generated by Django 2.2.7 on 2023-12-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0068_auto_20231209_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='av_schlagworte',
            field=models.TextField(blank=True, null=True, verbose_name='Av.-Schlagworte'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='rv_schlagworte',
            field=models.TextField(blank=True, null=True, verbose_name='Rv.-Schlagworte'),
        ),
    ]
