# Generated by Django 2.2.7 on 2025-01-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0069_auto_20231210_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ausgabe')),
            ],
            options={
                'verbose_name_plural': 'Ausgaben',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='gemeinderatsbeschluss',
            field=models.DateField(blank=True, null=True, verbose_name='Gemeinderatsbeschluss'),
        ),
        migrations.AddField(
            model_name='mzstaette',
            name='zeichen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zeichen'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='ausgabe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Ausgabe', verbose_name='Ausgabe'),
        ),
    ]
