# Generated by Django 2.2.7 on 2025-01-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0070_auto_20250122_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auflage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Auflage')),
            ],
            options={
                'verbose_name_plural': 'Auflagen',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='muenztyp',
            name='ausgabe',
        ),
        migrations.RemoveField(
            model_name='muenztyp',
            name='gemeinderatsbeschluss',
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='beschlussdatum',
            field=models.DateField(blank=True, null=True, verbose_name='Beschlussdatum'),
        ),
        migrations.DeleteModel(
            name='Ausgabe',
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='auflage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.Auflage', verbose_name='Auflage'),
        ),
    ]
