# Generated by Django 2.2.7 on 2025-03-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0071_auto_20250123_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlgKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sammlungskategorie',
                'verbose_name_plural': 'Sammlungskategorien',
            },
        ),
        migrations.AddField(
            model_name='slg',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sammlungen', to='slg.SlgKategorie'),
        ),
    ]
