# Generated by Django 2.2.7 on 2025-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0072_auto_20250315_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontaktanfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('betreff', models.CharField(max_length=200, verbose_name='Betreff')),
                ('nachricht', models.TextField(verbose_name='Nachricht')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('bearbeitet', models.BooleanField(default=False, verbose_name='Bearbeitet')),
            ],
            options={
                'verbose_name': 'Kontaktanfrage',
                'verbose_name_plural': 'Kontaktanfragen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
