# Generated by Django 2.2.7 on 2025-03-15 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slg', '0073_kontaktanfrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjektAenderung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('feld', models.CharField(max_length=100, verbose_name='Geändertes Feld')),
                ('alter_wert', models.TextField(verbose_name='Alter Wert')),
                ('neuer_wert', models.TextField(verbose_name='Neuer Wert')),
                ('begruendung', models.TextField(verbose_name='Begründung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('angenommen', 'Angenommen'), ('abgelehnt', 'Abgelehnt')], default='offen', max_length=20, verbose_name='Status')),
                ('bearbeitet_am', models.DateTimeField(blank=True, null=True, verbose_name='Bearbeitet am')),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bearbeitete_aenderungen', to=settings.AUTH_USER_MODEL, verbose_name='Bearbeitet von')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aenderungen', to='slg.Obj', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Objektänderung',
                'verbose_name_plural': 'Objektänderungen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
