# Generated by Django 2.2.7 on 2025-03-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0074_objektaenderung'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffizinSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Offizinsymbol/Monogramm')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('svg_link', models.URLField(blank=True, null=True, verbose_name='Link zum SVG')),
                ('uri_reference', models.URLField(blank=True, null=True, verbose_name='URI Referenz')),
            ],
            options={
                'verbose_name': 'Offizinsymbol/Monogramm',
                'verbose_name_plural': 'Offizinsymbole/Monogramme',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='av_offizin_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='av_muenztypen', to='slg.OffizinSymbol', verbose_name='AvOffizinsymbol'),
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='rv_offizin_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rv_muenztypen', to='slg.OffizinSymbol', verbose_name='RvOffizinsymbol'),
        ),
        migrations.AddField(
            model_name='obj',
            name='av_offizin_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='av_objekte', to='slg.OffizinSymbol', verbose_name='AvOffizinsymbol'),
        ),
        migrations.AddField(
            model_name='obj',
            name='rv_offizin_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rv_objekte', to='slg.OffizinSymbol', verbose_name='RvOffizinsymbol'),
        ),
    ]
