# Generated by Django 2.2.7 on 2025-04-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0075_auto_20250317_1259'),
    ]

    operations = [
 	migrations.RenameField(
            model_name='muenztyp',
            old_name='beschlussdatum',
            new_name='ausgabedatum',
        ),
    ]
