# Generated by Django 2.2.7 on 2025-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0076_rename_beschlussdatum_to_ausgabedatum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slgteil',
            options={'ordering': ['name'], 'verbose_name_plural': 'Sammlungsteile'},
        ),
        migrations.AddField(
            model_name='muenztyp',
            name='beschlussdatum',
            field=models.DateField(blank=True, null=True, verbose_name='Beschlussdatum'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='ausgabedatum',
            field=models.DateField(blank=True, null=True, verbose_name='Ausgabedatum'),
        ),
    ]
