# Generated by Django 2.2.7 on 2025-04-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0077_add_beschlussdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mzstaette',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='mzstaette',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='Längengrad'),
        ),
    ]
