# Generated by Django 2.2.7 on 2025-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0078_auto_20250413_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mzstaette',
            name='name_nom_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomisma ID'),
        ),
    ]
