# Generated by Django 2.2.7 on 2025-04-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0079_auto_20250417_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Zuletzt bearbeitet'),
        ),
    ]
