# Generated by Django 2.2.7 on 2025-04-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0080_muenztypobjektanzeige_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muenztypobjektanzeige',
            name='av_schlagworte',
        ),
        migrations.RemoveField(
            model_name='muenztypobjektanzeige',
            name='rv_schlagworte',
        ),
    ]
