# Generated by Django 2.2.7 on 2025-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0081_auto_20250423_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='av_schlagworte',
            field=models.TextField(blank=True, null=True, verbose_name='Av.-Schlagworte'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='rv_schlagworte',
            field=models.TextField(blank=True, null=True, verbose_name='Rv.-Schlagworte'),
        ),
    ]
