# Generated by Django 2.2.7 on 2025-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0082_auto_20250423_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='SlgTeil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SlgTeil'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='av_url',
            field=models.URLField(blank=True, null=True, verbose_name='Bild Avers'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='obj_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Objekt-ID'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='rv_url',
            field=models.URLField(blank=True, null=True, verbose_name='Bild Revers'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='thumbnail_av_url',
            field=models.URLField(blank=True, null=True, verbose_name='Thumbnail Avers'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='thumbnail_rv_url',
            field=models.URLField(blank=True, null=True, verbose_name='Thumbnail Revers'),
        ),
    ]
