# Generated by Django 2.2.7 on 2025-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0083_auto_20250423_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='Slg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slg'),
        ),
    ]
