# Generated by Django 2.2.7 on 2025-04-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0084_muenztypobjektanzeige_slg'),
    ]

    operations = [
        migrations.AddField(
            model_name='mzstaette',
            name='geonames',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Geonames ID'),
        ),
        migrations.AddField(
            model_name='mzstaette',
            name='ndpikmk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NDP-IKMK'),
        ),
    ]
