# Generated by Django 2.2.7 on 2025-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0085_auto_20250430_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muenztyp',
            options={'ordering': ('dat_von', 'dat_bis'), 'verbose_name': 'Münztyp', 'verbose_name_plural': 'Münztypen'},
        ),
        migrations.RemoveIndex(
            model_name='muenztyp',
            name='slg_muenzty_dat_von_b968b4_idx',
        ),
        migrations.AddIndex(
            model_name='muenztyp',
            index=models.Index(fields=['dat_von', 'dat_bis'], name='slg_muenzty_dat_von_9c70c1_idx'),
        ),
    ]
