# Generated by Django 2.2.7 on 2025-05-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0086_auto_20250518_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='slginformation',
            name='raw_personen',
            field=models.TextField(blank=True, verbose_name='Personen'),
        ),
    ]
