# Generated by Django 2.2.7 on 2025-06-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0087_slginformation_raw_personen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EreignisSchlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Schlagwort')),
                ('name_nom_id', models.CharField(blank=True, max_length=200, verbose_name='Nomisma ID')),
                ('synonyme', models.TextField(blank=True, null=True, verbose_name='Synonyme')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Ereignis-Schlagwort',
                'verbose_name_plural': 'Ereignis-Schlagworte',
                'ordering': ['kategorie__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EreignisSchlagwortKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategorie')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Ereignis-Schlagwort-Kategorie',
                'verbose_name_plural': 'Ereignis-Schlagwort-Kategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SlgInformationSchlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ereignisschlagwort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.EreignisSchlagwort', verbose_name='Schlagwort')),
                ('slginformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.SlgInformation')),
            ],
            options={
                'verbose_name': 'Ereignis-Schlagwort',
                'verbose_name_plural': 'Ereignis-Verschlagwortung',
                'ordering': ['ereignisschlagwort__kategorie__name', 'ereignisschlagwort__name'],
                'unique_together': {('slginformation', 'ereignisschlagwort')},
            },
        ),
        migrations.AddField(
            model_name='ereignisschlagwort',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slg.EreignisSchlagwortKategorie', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='slginformation',
            name='schlagworte',
            field=models.ManyToManyField(through='slg.SlgInformationSchlagwort', to='slg.EreignisSchlagwort', verbose_name='Schlagworte'),
        ),
    ]
