# Generated by Django 2.2.7 on 2025-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0088_auto_20250601_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='slginformation',
            name='raw_schlagworte',
            field=models.TextField(blank=True, verbose_name='Schlagworte'),
        ),
    ]
