# Generated by Django 2.2.7 on 2025-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0089_slginformation_raw_schlagworte'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mztyp_person',
            index=models.Index(fields=['Mztyp', 'idfk_Person'], name='slg_mztyp_p_Mztyp_i_c2a28b_idx'),
        ),
        migrations.AddIndex(
            model_name='mztyp_person',
            index=models.Index(fields=['Mztyp', 'idfk_PersonFunktion'], name='slg_mztyp_p_Mztyp_i_3c8554_idx'),
        ),
    ]
