# Generated by Django 2.2.7 on 2025-07-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0090_auto_20250629_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Paketname')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('ist_arbeitspaket', models.BooleanField(default=True, verbose_name='Ist Arbeitspaket')),
                ('online_freigegeben', models.BooleanField(default=False, verbose_name='Online freigegeben')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('bearbeitet_am', models.DateTimeField(auto_now=True, verbose_name='Bearbeitet am')),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Pakete',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjPaketZuweisung',
            fields=[
            ],
            options={
                'verbose_name': 'Paket-Zuweisung',
                'verbose_name_plural': 'Paket-Zuweisungen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('slg.obj',),
        ),
        migrations.AddField(
            model_name='obj',
            name='pakete',
            field=models.ManyToManyField(blank=True, to='slg.Paket', verbose_name='Pakete'),
        ),
    ]
