# Generated by Django 2.2.7 on 2025-07-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0091_auto_20250709_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objpaketzuweisung',
            options={'verbose_name': 'Paket-Zuweisung (Import)', 'verbose_name_plural': 'Paket-Zuweisungen (Import)'},
        ),
    ]
