# Generated by Django 2.2.7 on 2025-07-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0092_auto_20250709_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Titel')),
                ('sortierung', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Titel',
                'verbose_name_plural': 'Titel',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='obj',
            name='av_offizin_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='av_objekte', to='slg.OffizinSymbol', verbose_name='AvOffizinMonogrammSymbol'),
        ),
        migrations.AlterField(
            model_name='obj',
            name='rv_offizin_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rv_objekte', to='slg.OffizinSymbol', verbose_name='RvOffizinMonogrammSymbol'),
        ),
    ]
