# Generated by Django 2.2.7 on 2025-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0093_auto_20250723_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='slg',
            name='bilder_lokal',
            field=models.BooleanField(default=False, verbose_name='Bilder lokal auf Server speichern'),
        ),
        migrations.AddField(
            model_name='slg',
            name='lokaler_ordnername',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokaler Ordnername (optional)'),
        ),
        migrations.AddField(
            model_name='slgteil',
            name='bilder_lokal',
            field=models.BooleanField(default=False, verbose_name='Bilder lokal auf Server speichern'),
        ),
        migrations.AddField(
            model_name='slgteil',
            name='lokaler_unterordner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokaler Unterordner (optional)'),
        ),
    ]
