# Generated by Django 2.2.7 on 2025-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0094_auto_20250813_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='zusammen_gefundene_muenzen',
            field=models.ManyToManyField(blank=True, related_name='_fund_zusammen_gefundene_muenzen_+', to='slg.Fund', verbose_name='Zusammen gefundene Münzen'),
        ),
    ]
