# Generated by Django 2.2.7 on 2026-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0095_auto_20251101_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muenztyp',
            options={'verbose_name': 'Münztyp', 'verbose_name_plural': 'Münztypen'},
        ),
        migrations.AlterModelOptions(
            name='obj',
            options={'verbose_name': 'Objekt', 'verbose_name_plural': 'Objekte'},
        ),
        migrations.AddIndex(
            model_name='obj',
            index=models.Index(fields=['Slg', 'SlgTeil'], name='slg_obj_Slg_id_ce0ea3_idx'),
        ),
    ]
