# Generated by Django 2.2.7 on 2026-02-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0096_auto_20260220_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='av_bildtyp_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.AvBildtyp', verbose_name='AvBildtyp (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='herstellung_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Herstellung', verbose_name='Herstellung (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='metall_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Metall', verbose_name='Material (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='muenzstand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Muenzstand', verbose_name='Münzstand (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='mzstaette_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Mzstaette', verbose_name='Münzstätte (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='nominal_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Nominal', verbose_name='Nominal (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='objekttyp_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Objekttyp', verbose_name='Objekttyp (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='region_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Region', verbose_name='Region (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='rv_bildtyp_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.RvBildtyp', verbose_name='RvBildtyp (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='slg_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Slg', verbose_name='Sammlung (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='slgteil_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.SlgTeil', verbose_name='Sammlungsteil (FK)'),
        ),
        migrations.AddField(
            model_name='muenztypobjektanzeige',
            name='typ_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slg.Muenztyp', verbose_name='Münztyp (FK)'),
        ),
        migrations.CreateModel(
            name='MtoaPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appears_on_rev', models.BooleanField(default=False)),
                ('funktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.PersonFunktion')),
                ('mtoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.MuenztypObjektAnzeige')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slg.Person')),
            ],
            options={
                'verbose_name': 'MTOA Person',
                'verbose_name_plural': 'MTOA Personen',
            },
        ),
        migrations.AddIndex(
            model_name='mtoaperson',
            index=models.Index(fields=['person', 'funktion', 'appears_on_rev'], name='slg_mtoaper_person__dffcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='mtoaperson',
            index=models.Index(fields=['mtoa'], name='slg_mtoaper_mtoa_id_7bfd6f_idx'),
        ),
    ]
