# Generated by Django 5.2.2 on 2026-04-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0097_auto_20260220_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='zusammen_gefundene_muenzen',
            field=models.ManyToManyField(blank=True, to='slg.fund', verbose_name='Zusammen gefundene Münzen'),
        ),
        migrations.AlterField(
            model_name='muenztyp',
            name='Konkordanz',
            field=models.ManyToManyField(blank=True, to='slg.muenztyp', verbose_name='Konkordanz'),
        ),
    ]
