"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

def _get_secret_key():
    key_file = os.getenv('DJANGO_SECRET_KEY_FILE')
    if key_file:
        try:
            return Path(key_file).read_text(encoding='utf8').strip()
        except (FileNotFoundError, OSError):
            pass
    return os.getenv('DJANGO_SECRET_KEY', 'dev-only-change-me')

SECRET_KEY = _get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('1', 'true', 'yes', 'on')

# ALLOWED_HOSTS = ['46.101.237.189']
ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', 'https://eligius.donau-uni.ac.at').split(',')
    if origin.strip()
]
SITE_ID = int(os.getenv('DJANGO_SITE_ID', '1'))

# Application definition

INSTALLED_APPS = [
    'model_clone',
    'adminactions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'slg',
    'import_export',
    'django_select2',
    # 'debug_toolbar' will be appended only in DEBUG mode
    'rest_framework',
    'rest_framework.authtoken',
    #'qurl_templatetag',
    'bootstrap3',
    'bootstrap_modal_forms',
    'widget_tweaks',
    'django_admin_listfilter_dropdown',
    'nested_admin',
    'corsheaders',
    #'crispy_forms',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Oder entferne diese Zeile komplett
    ]
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
    INTERNAL_IPS = ['127.0.0.1']

cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
cors_origins_list = [o.strip() for o in cors_origins_env.split(',') if o.strip()]
if cors_origins_list:
    CORS_ALLOWED_ORIGINS = cors_origins_list
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'slg.webmcp.webmcp_enabled',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproject.wsgi.application'
ASGI_APPLICATION = 'djangoproject.asgi.application'

# Public read-only MCP. No deployment-specific hosts in application code.
ELIGIUS_MCP_ENABLED = os.getenv('ELIGIUS_MCP_ENABLED', '0').lower() in ('1', 'true', 'yes')
ELIGIUS_EDITOR_MCP_ENABLED = os.getenv('ELIGIUS_EDITOR_MCP_ENABLED', '0').lower() in ('1', 'true', 'yes')
ELIGIUS_WEBMCP_ENABLED = os.getenv('ELIGIUS_WEBMCP_ENABLED', '0').lower() in ('1', 'true', 'yes')
ELIGIUS_PUBLIC_BASE_URL = os.getenv('ELIGIUS_PUBLIC_BASE_URL', '').rstrip('/')
ELIGIUS_MCP_ALLOWED_HOSTS = [v.strip() for v in os.getenv(
    'ELIGIUS_MCP_ALLOWED_HOSTS', 'localhost:*,127.0.0.1:*').split(',') if v.strip()]
ELIGIUS_MCP_ALLOWED_ORIGINS = [v.strip() for v in os.getenv(
    'ELIGIUS_MCP_ALLOWED_ORIGINS', '').split(',') if v.strip()]


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

def _get_database_password(default=None):
    filename = os.getenv('DATABASE_PASSWORD_FILE')
    if filename:
        try:
            return Path(filename).read_text(encoding='utf8').strip()
        except (FileNotFoundError, OSError):
            pass
    return os.getenv('DATABASE_PASSWORD', default)

db_cnf_path = os.getenv('DJANGO_DB_CNF_PATH')
has_docker_db_env = any(os.getenv(k) for k in ('DATABASE_NAME', 'DATABASE_USER', 'DATABASE_PASSWORD', 'DATABASE_PASSWORD_FILE', 'DATABASE_HOST'))

# Prefer DJANGO_DB_CNF_PATH if explicitly configured.
# Otherwise, if Docker/production environment DB variables are provided, use them.
# Fall back to default .cnf location for legacy deployments without env vars.
if db_cnf_path or not has_docker_db_env:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'OPTIONS': {
                'read_default_file': db_cnf_path or '/djangoproject/auth/mysql.cnf',
                'charset': 'utf8mb4',
            },
        }
    }
else:
    db_port = os.getenv('DATABASE_PORT')
    default_db = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_NAME', 'django'),
        'USER': os.getenv('DATABASE_USER', 'django'),
        'PASSWORD': _get_database_password('password'),
        'HOST': os.getenv('DATABASE_HOST', 'localhost'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
    if db_port:
        default_db['PORT'] = db_port
    DATABASES = {
        'default': default_db,
    }

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Keep legacy AutoField behavior for old migrations/models (avoids noisy W042 warnings)
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT', '/djangoproject/site/public/static')

SLG_BILDER_STATIC_SUBDIR = 'slg_bilder'
