# docker compose for eligius containing gunicorn webapp server and mariadb database
# exposes http endpoint for nginx webserver at:  /run/eligius/http.socket

# initial database in /database-init as .sql file (or .sql.gz)
# passwords as text files: db_root_password.txt, db_password.txt, django_secret.txt

name: eligius

services:
  webapp:
    image: dwb-gitlab.donau-uni.ac.at/zms/eligius:latest
    environment:
      WEB_CONCURRENCY: 8
      PROJECT_NAME: eligius
      DJANGO_DEBUG: false
      DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret
      DJANGO_ALLOWED_HOSTS: eligius.donau-uni.ac.at
      DJANGO_STATIC_ROOT: /app/static
      DATABASE_NAME: eligius
      DATABASE_USER: eligius
      DATABASE_PASSWORD_FILE: /run/secrets/db_password
      DATABASE_HOST: /run/mysqld/mysqld.sock
      CORS_ALLOWED_ORIGINS: https://eligius.donau-uni.ac.at
      GUNICORN_BIND: unix:/run/eligius/http.socket
    restart: unless-stopped
    volumes:
      - type: bind
        source: /run/eligius
        target: /run/eligius
      - type: volume
        source: mysql-run
        target: /run/mysqld
        read_only: true
      - type: bind
        source: /srv/http/eligius/public/static
        target: /app/static
        bind:
          create_host_path: true
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - django_secret
      - db_password

  db:
    image: mariadb:lts
    environment:
      MARIADB_DATABASE: eligius
      MARIADB_USER: eligius
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-run:/run/mysqld
      - mysql-data:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d:ro
    secrets:
      - db_root_password
      - db_password

volumes:
  mysql-run:
  mysql-data:

secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt
  django_secret:
    file: django_secret.txt
